import type { Metadata } from 'next';
import './globals.css';
import { ThirdwebProvider } from 'thirdweb/react';
import Head from '@/components/layouts/Head';
// import WalletProvider from '@/providers/WalletProvider';
import LayoutDesktop from './layoutDesktop';
import LayoutMobile from './layoutMobile';
export const metadata: Metadata = {
  title: 'Givabit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head />
      <body>
        <ThirdwebProvider>
          <LayoutMobile>{children}</LayoutMobile>
          <LayoutDesktop>{children}</LayoutDesktop>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
