import type { Metadata } from 'next';
import './globals.css';
import Head from '@/components/layouts/Head';
import MediaLoader from '@/components/layouts/MediaLoader';
import MediaProvider from '@/providers/MediaProvider';
import WalletProvider from '@/providers/WalletProvider';
import { Media } from '@/utils/media';
import LayoutDesktop from './layoutDesktop';
import LayoutMobile from './layoutMobile';

export const metadata: Metadata = {
  title: 'Givabit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head />
      <WalletProvider>
        <MediaProvider>
          <body>
            <MediaLoader />
            <Media greaterThanOrEqual='md'>
              <LayoutDesktop>{children}</LayoutDesktop>
            </Media>
            <Media lessThan='md'>
              <LayoutMobile>{children}</LayoutMobile>
            </Media>
          </body>
        </MediaProvider>
      </WalletProvider>
    </html>
  );
}
