import type { Metadata } from 'next';
import './globals.css';
import Head from '@/components/layouts/Head';
import WalletProvider from '@/providers/WalletProvider';
import LayoutDesktop from './layoutDesktop';
import LayoutMobile from './layoutMobile';

export const metadata: Metadata = {
  title: 'Givabit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head />
      <WalletProvider>
        <body>
          <LayoutMobile>{children}</LayoutMobile>
          <LayoutDesktop>{children}</LayoutDesktop>
        </body>
      </WalletProvider>
    </html>
  );
}
